
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuhoxvrkpsrsyjqpcrhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aG94dnJrcHNyc3lqcXBjcmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Njg4MjcsImV4cCI6MjA1ODI0NDgyN30.nJXAr-AzFiiQCm9QJDKRH5hMzrRaB9nf_R-qihuqais";

// Create and export the supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
  },
  global: {
    fetch: (...args: Parameters<typeof fetch>) => fetch(...args),
  },
});

// Helper function to get public URL for storage items
export const getPublicUrl = (bucket: string, path: string) => {
  try {
    const { data } = supabase.storage.from(bucket).getPublicUrl(path);
    return data.publicUrl;
  } catch (error) {
    console.error(`Error getting public URL for ${path}:`, error);
    return null;
  }
};
