// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxsltsktjzgmoqwarhps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4c2x0c2t0anpnbW9xd2FyaHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjE1MDgsImV4cCI6MjA1ODU5NzUwOH0.ZFHmrgRoczoSubLAvqD9sKBs7uHND6oMgFM9S70nfvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);